CREATE TABLE [dbo].[Products]
(
	[ProductID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [DateCreated] DATETIME NOT NULL DEFAULT GETDATE(), 
    [CreatedBy] INT NOT NULL DEFAULT 0, 
    [DateUpdated] DATETIME NOT NULL DEFAULT GETDATE(), 
    [UpdatedBy] INT NOT NULL DEFAULT 0, 
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [Name] NTEXT NOT NULL, 
    [Price] INT NOT NULL, 
    [Quantity] INT NOT NULL, 
    [ImageURL] NVARCHAR(1024) NOT NULL
)
